spring.application.name=email-writer-sb

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=
gemini.api.key=AIzaSyCpXYdt1qa6KMQO081UovPBJJAe8cppg4w
###
#gemini.api.url=${GEMINI_URL}
#
#gemini.api.key=${GEMINI_KEY}
#AIzaSyCpXYdt1qa6KMQO081UovPBJJAe8cppg4w